import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.LocalDate;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Tests the assignment database methods.
 *
 * @author Estefan Vicencio
 * @version 0.1.0
 * @since 8/2/2026
 */
public class AssignmentDaoTest {

  private Connection connection;
  private AssignmentDao assignmentDao;

  /**
   * Makes a test database before each test.
   */
  @BeforeEach
  public void setUp() throws Exception {
    connection =
        DriverManager.getConnection(
            "jdbc:h2:mem:assignmentTest");

    Statement statement =
        connection.createStatement();

    statement.execute(
        "DROP TABLE IF EXISTS assignments");

    statement.execute(
        "CREATE TABLE assignments ("
            + "assignment_id INTEGER "
            + "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            + "class_id INTEGER NOT NULL, "
            + "title VARCHAR(255) NOT NULL, "
            + "description VARCHAR(500), "
            + "due_date VARCHAR(10) NOT NULL, "
            + "points_possible DOUBLE NOT NULL, "
            + "status VARCHAR(50) NOT NULL"
            + ")");

    statement.close();

    assignmentDao =
        new AssignmentDao(connection);
  }

  /**
   * Closes the test database after each test.
   */
  @AfterEach
  public void tearDown() throws Exception {
    connection.close();
  }

  /**
   * Tests adding and finding an assignment.
   */
  @Test
  public void insertAndFindTest() throws Exception {
    Assignment assignment =
        new Assignment(
            1,
            "Java Homework",
            "Finish the DAO",
            LocalDate.of(2026, 8, 10),
            100.0,
            "Not Started");

    assignmentDao.insert(assignment);

    Assignment savedAssignment =
        assignmentDao.findById(
            assignment.getAssignmentId());

    assertNotNull(savedAssignment);

    assertEquals(
        "Java Homework",
        savedAssignment.getTitle());

    assertEquals(
        100.0,
        savedAssignment.getPointsPossible(),
        0.001);
  }
}