import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests for AuthService, run against an in-memory H2 database.
 *
 * Each test starts with a blank users table and a real UserDao wired to the H2
 * connection, so these exercise the whole path from AuthService through the DAO
 * to the database. The table uses the same H2 syntax as UserDaoTest.
 *
 * @author Bay Shahryar
 * @version 0.1.0
 * @since 8/8/26
 */
public class AuthServiceTest {

    private Connection connection;
    private AuthService authService;

    /**
     * Makes a test database and a fresh AuthService before each test.
     */
    @BeforeEach
    public void setUp() throws SQLException {
        connection = DriverManager.getConnection("jdbc:h2:mem:authTest");

        Statement statement = connection.createStatement();
        statement.execute("DROP TABLE IF EXISTS users");
        statement.execute(
                "CREATE TABLE users ("
                        + "user_id INTEGER "
                        + "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "username VARCHAR(50) UNIQUE NOT NULL, "
                        + "password VARCHAR(100) NOT NULL, "
                        + "role VARCHAR(20) NOT NULL"
                        + ")");
        statement.close();

        authService = new AuthService(new UserDao(connection));
    }

    /**
     * Closes the test database after each test.
     */
    @AfterEach
    public void tearDown() throws SQLException {
        connection.close();
    }

    // ----- register: the happy path -----

    @Test
    public void registerValidAccountSucceeds() {
        AuthResult result =
                authService.register("bay", "pass123", "pass123", "STUDENT");

        assertTrue(result.isSuccess());
        assertNotNull(result.getUser());
        assertTrue(result.getUser().getUserId() > 0);
        assertEquals("bay", result.getUser().getUsername());
        assertEquals("STUDENT", result.getUser().getRole());
    }

    // ----- register: validation failures -----

    @Test
    public void registerBlankUsernameFails() {
        AuthResult result =
                authService.register("  ", "pass123", "pass123", "STUDENT");

        assertFalse(result.isSuccess());
        assertNull(result.getUser());
    }

    @Test
    public void registerBlankPasswordFails() {
        AuthResult result =
                authService.register("bay", "", "", "STUDENT");

        assertFalse(result.isSuccess());
        assertNull(result.getUser());
    }

    @Test
    public void registerMissingRoleFails() {
        AuthResult result =
                authService.register("bay", "pass123", "pass123", "");

        assertFalse(result.isSuccess());
        assertNull(result.getUser());
    }

    @Test
    public void registerInvalidRoleFails() {
        AuthResult result =
                authService.register("bay", "pass123", "pass123", "ADMIN");

        assertFalse(result.isSuccess());
        assertNull(result.getUser());
    }

    @Test
    public void registerMismatchedPasswordsFails() {
        AuthResult result =
                authService.register("bay", "pass123", "different", "STUDENT");

        assertFalse(result.isSuccess());
        assertNull(result.getUser());
    }

    @Test
    public void registerDuplicateUsernameFails() {
        authService.register("bay", "pass123", "pass123", "STUDENT");

        AuthResult result =
                authService.register("bay", "other", "other", "TEACHER");

        assertFalse(result.isSuccess());
        assertNull(result.getUser());
    }

    // ----- login -----

    @Test
    public void loginWithValidCredentialsSucceeds() {
        authService.register("bay", "pass123", "pass123", "STUDENT");

        AuthResult result = authService.login("bay", "pass123");

        assertTrue(result.isSuccess());
        assertNotNull(result.getUser());
        assertEquals("bay", result.getUser().getUsername());
    }

    @Test
    public void loginWithWrongPasswordFails() {
        authService.register("bay", "pass123", "pass123", "STUDENT");

        AuthResult result = authService.login("bay", "wrongpass");

        assertFalse(result.isSuccess());
        assertNull(result.getUser());
    }

    @Test
    public void loginUnknownUsernameFails() {
        AuthResult result = authService.login("nobody", "whatever");

        assertFalse(result.isSuccess());
        assertNull(result.getUser());
    }

    @Test
    public void loginBlankUsernameFails() {
        AuthResult result = authService.login("", "pass123");

        assertFalse(result.isSuccess());
        assertNull(result.getUser());
    }

    @Test
    public void loginBlankPasswordFails() {
        AuthResult result = authService.login("bay", "");

        assertFalse(result.isSuccess());
        assertNull(result.getUser());
    }

    /**
     * The generic error is the same whether the username is unknown or the
     * password is wrong, so the app never reveals which usernames exist.
     */
    @Test
    public void loginWrongPasswordAndUnknownUserGiveSameMessage() {
        authService.register("bay", "pass123", "pass123", "STUDENT");

        AuthResult wrongPassword = authService.login("bay", "wrongpass");
        AuthResult unknownUser = authService.login("ghost", "wrongpass");

        assertEquals(wrongPassword.getMessage(), unknownUser.getMessage());
    }
}