import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.List;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.testfx.framework.junit5.ApplicationTest;

import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TableView;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

/**
 * Tests the Grade model, GradeDao database operations, grade display logic,
 * GradesController behavior, and the grades.fxml user interface.
 *
 * This file intentionally keeps all grade-related tests together. The large
 * section comments separate the different types of testing.
 *
 * @author Lily Keus
 * @version 0.2.0
 * @since 8/11/2026
 */
public class GradeTest extends ApplicationTest {

    private Connection connection;
    private GradeDao gradeDao;
    private Stage stage;

    @Override
    public void start(Stage stage) {
        this.stage = stage;
        stage.setScene(new Scene(new StackPane(), 800, 600));
        stage.show();
    }

    @BeforeEach
    public void setUpDatabase() throws Exception {
        connection = DriverManager.getConnection("jdbc:h2:mem:gradeTest");

        try (Statement statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS grades");
            statement.execute(
                    "CREATE TABLE grades ("
                            + "grade_id INTEGER "
                            + "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                            + "enrollment_id INTEGER NOT NULL, "
                            + "assignment_id INTEGER NOT NULL, "
                            + "grade DOUBLE NOT NULL, "
                            + "weight DOUBLE NOT NULL"
                            + ")");
        }

        gradeDao = new GradeDao(connection);
    }

    @AfterEach
    public void tearDownDatabase() throws Exception {
        Session.clear();

        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
    }

    /*
     * ========================================================================
     *                         GRADE MODEL TESTS
     * ========================================================================
     * These tests verify the Grade data object itself, including construction,
     * mutation, equality, hashCode, and toString behavior.
     */

    @Test
    public void gradeConstructorAndGettersTest() {
        Grade grade = new Grade(7, 11, 22, 95.5, 0.25);

        assertEquals(7, grade.getGradeId());
        assertEquals(11, grade.getEnrollmentId());
        assertEquals(22, grade.getAssignmentId());
        assertEquals(95.5, grade.getGrade(), 0.001);
        assertEquals(0.25, grade.getWeight(), 0.001);
    }

    @Test
    public void newGradeStartsWithZeroIdTest() {
        Grade grade = new Grade(11, 22, 88.0, 0.40);

        assertEquals(0, grade.getGradeId());
    }

    @Test
    public void gradeSettersChangeEveryFieldTest() {
        Grade grade = new Grade(1, 2, 70.0, 0.10);

        grade.setGradeId(9);
        grade.setEnrollmentId(10);
        grade.setAssignmentId(20);
        grade.setGrade(99.0);
        grade.setWeight(0.75);

        assertEquals(9, grade.getGradeId());
        assertEquals(10, grade.getEnrollmentId());
        assertEquals(20, grade.getAssignmentId());
        assertEquals(99.0, grade.getGrade(), 0.001);
        assertEquals(0.75, grade.getWeight(), 0.001);
    }

    @Test
    public void equalGradesHaveEqualHashCodesTest() {
        Grade first = new Grade(3, 4, 5, 91.0, 0.30);
        Grade second = new Grade(3, 4, 5, 91.0, 0.30);

        assertEquals(first, second);
        assertEquals(first.hashCode(), second.hashCode());
    }

    @Test
    public void changingOneGradeFieldBreaksEqualityTest() {
        Grade first = new Grade(3, 4, 5, 91.0, 0.30);
        Grade second = new Grade(3, 4, 5, 91.0, 0.30);

        second.setGrade(90.0);

        assertNotEquals(first, second);
        assertNotEquals(first, null);
        assertNotEquals(first, "not a grade");
    }

    @Test
    public void gradeToStringContainsImportantValuesTest() {
        Grade grade = new Grade(3, 4, 5, 91.0, 0.30);
        String text = grade.toString();

        assertTrue(text.contains("gradeId=3"));
        assertTrue(text.contains("enrollmentId=4"));
        assertTrue(text.contains("assignmentId=5"));
        assertTrue(text.contains("grade=91.0"));
        assertTrue(text.contains("weight=0.3"));
    }

    /*
     * ========================================================================
     *                         GRADE DAO TESTS
     * ========================================================================
     * These are database integration tests using H2. They test the complete
     * CRUD path plus filtering methods and failure cases instead of only the
     * successful insert/find path.
     */

    @Test
    public void insertAndFindByIdTest() throws Exception {
        Grade grade = new Grade(1, 2, 95.5, 0.25);

        gradeDao.insert(grade);

        assertTrue(grade.getGradeId() > 0);

        Grade savedGrade = gradeDao.findById(grade.getGradeId());

        assertNotNull(savedGrade);
        assertEquals(grade, savedGrade);
    }

    @Test
    public void findByIdReturnsNullForMissingGradeTest() throws Exception {
        assertNull(gradeDao.findById(999999));
    }

    @Test
    public void findAllReturnsEveryGradeInIdOrderTest() throws Exception {
        Grade first = new Grade(1, 10, 75.0, 0.20);
        Grade second = new Grade(2, 20, 85.0, 0.30);
        Grade third = new Grade(3, 30, 95.0, 0.50);

        gradeDao.insert(first);
        gradeDao.insert(second);
        gradeDao.insert(third);

        List<Grade> grades = gradeDao.findAll();

        assertEquals(3, grades.size());
        assertEquals(first, grades.get(0));
        assertEquals(second, grades.get(1));
        assertEquals(third, grades.get(2));
    }

    @Test
    public void findByEnrollmentIdDoesNotLeakOtherStudentsGradesTest() throws Exception {
        Grade wantedOne = new Grade(100, 1, 88.0, 0.25);
        Grade otherEnrollment = new Grade(200, 1, 99.0, 0.25);
        Grade wantedTwo = new Grade(100, 2, 77.0, 0.25);

        gradeDao.insert(wantedOne);
        gradeDao.insert(otherEnrollment);
        gradeDao.insert(wantedTwo);

        List<Grade> grades = gradeDao.findByEnrollmentId(100);

        assertEquals(2, grades.size());
        assertTrue(grades.stream().allMatch(g -> g.getEnrollmentId() == 100));
        assertTrue(grades.contains(wantedOne));
        assertTrue(grades.contains(wantedTwo));
        assertFalse(grades.contains(otherEnrollment));
    }

    @Test
    public void findByAssignmentIdDoesNotIncludeOtherAssignmentsTest() throws Exception {
        Grade wantedOne = new Grade(1, 50, 88.0, 0.25);
        Grade otherAssignment = new Grade(1, 60, 99.0, 0.25);
        Grade wantedTwo = new Grade(2, 50, 77.0, 0.25);

        gradeDao.insert(wantedOne);
        gradeDao.insert(otherAssignment);
        gradeDao.insert(wantedTwo);

        List<Grade> grades = gradeDao.findByAssignmentId(50);

        assertEquals(2, grades.size());
        assertTrue(grades.stream().allMatch(g -> g.getAssignmentId() == 50));
        assertTrue(grades.contains(wantedOne));
        assertTrue(grades.contains(wantedTwo));
        assertFalse(grades.contains(otherAssignment));
    }

    @Test
    public void updatePersistsEveryChangedFieldTest() throws Exception {
        Grade grade = new Grade(1, 2, 70.0, 0.10);
        gradeDao.insert(grade);

        grade.setEnrollmentId(10);
        grade.setAssignmentId(20);
        grade.setGrade(98.5);
        grade.setWeight(0.80);

        gradeDao.update(grade);

        Grade updated = gradeDao.findById(grade.getGradeId());

        assertNotNull(updated);
        assertEquals(10, updated.getEnrollmentId());
        assertEquals(20, updated.getAssignmentId());
        assertEquals(98.5, updated.getGrade(), 0.001);
        assertEquals(0.80, updated.getWeight(), 0.001);
    }

    @Test
    public void deleteActuallyRemovesGradeTest() throws Exception {
        Grade grade = new Grade(1, 2, 70.0, 0.10);
        gradeDao.insert(grade);

        gradeDao.delete(grade.getGradeId());

        assertNull(gradeDao.findById(grade.getGradeId()));
        assertTrue(gradeDao.findAll().isEmpty());
    }

    /*
     * ========================================================================
     *                    DAO EDGE / FAILURE CASE TESTS
     * ========================================================================
     * These deliberately use IDs that do not exist. Silent success here could
     * hide application bugs, so GradeDao is expected to report the problem.
     */

    @Test
    public void updatingMissingGradeThrowsSQLExceptionTest() {
        Grade missing = new Grade(999999, 1, 2, 80.0, 0.25);

        SQLException exception = assertThrows(
                SQLException.class,
                () -> gradeDao.update(missing));

        assertTrue(exception.getMessage().contains("999999"));
    }

    @Test
    public void deletingMissingGradeThrowsSQLExceptionTest() {
        SQLException exception = assertThrows(
                SQLException.class,
                () -> gradeDao.delete(999999));

        assertTrue(exception.getMessage().contains("999999"));
    }

    /*
     * ========================================================================
     *                   GRADES CONTROLLER LOGIC TESTS
     * ========================================================================
     * No reflection is used. GradeRow and ViewMode are public parts of the
     * controller, so their display logic can be tested normally.
     */

    @Test
    public void gradeRowFormatsExistingScoreAndCoursePercentTest() {
        Grade grade = new Grade(4, 8, 45.0, 0.50);

        GradesController.GradeRow row = new GradesController.GradeRow(
                grade,
                8,
                3,
                "Final Exam",
                LocalDate.of(2026, 8, 20),
                50.0,
                12,
                "student1",
                "CST 338",
                4,
                25.0);

        assertEquals("45.0 / 50.0", row.getScoreText());
        assertEquals("25.00%", row.getCoursePercentText());
        assertEquals("Final Exam", row.getAssignmentName());
        assertEquals("student1", row.getStudentName());
        assertEquals("CST 338", row.getCourseName());
    }

    @Test
    public void gradeRowWithNoGradeUsesDashInsteadOfFakeZeroTest() {
        GradesController.GradeRow row = new GradesController.GradeRow(
                null,
                8,
                3,
                "Final Exam",
                LocalDate.of(2026, 8, 20),
                50.0,
                12,
                "student1",
                "CST 338",
                4,
                25.0);

        assertEquals("— / 50.0", row.getScoreText());
        assertNull(row.getGrade());
    }

    @Test
    public void viewModeDisplaysUserFriendlyTextTest() {
        assertEquals("My grades", GradesController.ViewMode.STUDENT.toString());
        assertEquals("Students", GradesController.ViewMode.TEACHER_BY_STUDENT.toString());
        assertEquals("Assignments", GradesController.ViewMode.TEACHER_BY_ASSIGNMENT.toString());
        assertEquals("Logged Out", GradesController.ViewMode.LOGGED_OUT.toString());
    }

    @Test
    public void gradeRowReturnsEveryStoredValueTest() {

        Grade grade = new Grade(15, 25, 40, 87.5, 0.30);
        LocalDate dueDate = LocalDate.of(2026, 8, 25);

        GradesController.GradeRow row = new GradesController.GradeRow(
                grade,
                40,
                7,
                "Unit Test",
                dueDate,
                100.0,
                25,
                "testStudent",
                "Software Design",
                15,
                20.0
        );

        assertEquals(grade, row.getGrade());
        assertEquals(40, row.getAssignmentId());
        assertEquals(7, row.getClassId());
        assertEquals("Unit Test", row.getAssignmentName());
        assertEquals(dueDate, row.getDueDate());
        assertEquals(100.0, row.getPointsPossible(), 0.001);
        assertEquals(25, row.getStudentId());
        assertEquals("testStudent", row.getStudentName());
        assertEquals("Software Design", row.getCourseName());
        assertEquals(15, row.getEnrollmentId());
        assertEquals(20.0, row.getCoursePercent(), 0.001);
    }

    @Test
    public void gradeRowCoursePercentRoundsToTwoDecimalPlacesTest() {

        GradesController.GradeRow row = new GradesController.GradeRow(
                null,
                1,
                2,
                "Quiz",
                LocalDate.of(2026, 8, 20),
                10.0,
                3,
                "student",
                "CST 338",
                4,
                33.336
        );

        assertEquals("33.34%", row.getCoursePercentText());
    }

    @Test
    public void gradeRowZeroScoreIsDifferentFromMissingGradeTest() {

        Grade zeroGrade = new Grade(1, 2, 0.0, 0.25);

        GradesController.GradeRow zeroRow = new GradesController.GradeRow(
                zeroGrade,
                2,
                3,
                "Exam",
                LocalDate.of(2026, 8, 20),
                50.0,
                4,
                "student",
                "CST 338",
                1,
                25.0
        );

        GradesController.GradeRow missingRow = new GradesController.GradeRow(
                null,
                2,
                3,
                "Exam",
                LocalDate.of(2026, 8, 20),
                50.0,
                4,
                "student",
                "CST 338",
                1,
                25.0
        );

        assertEquals("0.0 / 50.0", zeroRow.getScoreText());
        assertEquals("— / 50.0", missingRow.getScoreText());

        assertNotEquals(
                zeroRow.getScoreText(),
                missingRow.getScoreText()
        );
    }

    @Test
    public void gradeRowScoreTextUsesCurrentGradeValueTest() {

        Grade grade = new Grade(1, 2, 75.0, 0.25);

        GradesController.GradeRow row = new GradesController.GradeRow(
                grade,
                2,
                3,
                "Exam",
                LocalDate.of(2026, 8, 20),
                100.0,
                4,
                "student",
                "CST 338",
                1,
                25.0
        );

        assertEquals("75.0 / 100.0", row.getScoreText());

        grade.setGrade(92.5);

        assertEquals("92.5 / 100.0", row.getScoreText());
    }

    @Test
    public void loggedOutControlsAreAlsoUnmanagedTest() throws Exception {

        Session.clear();

        URL gradesFxml = GradeTest.class.getResource("/grades.fxml");
        assertNotNull(gradesFxml);

        Parent root = new FXMLLoader(gradesFxml).load();

        interact(() ->
                stage.setScene(new Scene(root, 1180, 760))
        );

        ComboBox<?> viewByComboBox =
                lookup("#viewByComboBox").queryAs(ComboBox.class);

        ComboBox<?> classSelectionComboBox =
                lookup("#classSelectionComboBox").queryAs(ComboBox.class);

        ComboBox<?> selectionComboBox =
                lookup("#selectionComboBox").queryAs(ComboBox.class);

        Label overallGradeLabel =
                lookup("#overallGradeLabel").queryAs(Label.class);

        Label tableTitleLabel =
                lookup("#tableTitleLabel").queryAs(Label.class);

        assertFalse(viewByComboBox.isManaged());
        assertFalse(classSelectionComboBox.isManaged());
        assertFalse(selectionComboBox.isManaged());

        assertFalse(overallGradeLabel.isManaged());
        assertFalse(tableTitleLabel.isManaged());
    }

    @Test
    public void gradesFxmlBuildsAllExpectedTableColumnsTest() throws Exception {

        Session.clear();

        URL gradesFxml = GradeTest.class.getResource("/grades.fxml");
        assertNotNull(gradesFxml);

        Parent root = new FXMLLoader(gradesFxml).load();

        interact(() ->
                stage.setScene(new Scene(root, 1180, 760))
        );

        TableView<?> gradesTable =
                lookup("#gradesTable").queryAs(TableView.class);

        assertNotNull(gradesTable);

        assertEquals(5, gradesTable.getColumns().size());

        assertEquals(
                "Assignment",
                gradesTable.getColumns().get(0).getText()
        );

        assertEquals(
                "Student Name",
                gradesTable.getColumns().get(1).getText()
        );

        assertEquals(
                "Due",
                gradesTable.getColumns().get(2).getText()
        );

        assertEquals(
                "Score",
                gradesTable.getColumns().get(3).getText()
        );

        assertEquals(
                "Class %",
                gradesTable.getColumns().get(4).getText()
        );
    }

    @Test
    public void loggedOutViewHidesDataColumnsTest() throws Exception {

        Session.clear();

        URL gradesFxml = GradeTest.class.getResource("/grades.fxml");
        assertNotNull(gradesFxml);

        Parent root = new FXMLLoader(gradesFxml).load();

        interact(() ->
                stage.setScene(new Scene(root, 1180, 760))
        );

        TableView<?> gradesTable =
                lookup("#gradesTable").queryAs(TableView.class);

        assertFalse(gradesTable.isVisible());

        assertFalse(
                gradesTable.getColumns().get(0).isVisible(),
                "Assignment column should be hidden"
        );

        assertFalse(
                gradesTable.getColumns().get(1).isVisible(),
                "Student column should be hidden"
        );

        assertFalse(
                gradesTable.getColumns().get(2).isVisible(),
                "Due date column should be hidden"
        );

        assertFalse(
                gradesTable.getColumns().get(4).isVisible(),
                "Class percentage column should be hidden"
        );
    }

    /*
     * ========================================================================
     *                          TESTFX UI TEST
     * ========================================================================
     * Critical edge case: grades.fxml is opened while nobody is logged in.
     * This verifies that the FXML loads with GradesController, initialization
     * runs successfully, private controller handlers are wired by FXML, and
     * grade data controls are hidden from an unauthenticated user.
     */

    @Test
    public void loggedOutUserCannotSeeGradeControlsTest() throws Exception {
        Session.clear();

        URL gradesFxml = GradeTest.class.getResource("/grades.fxml");
        assertNotNull(gradesFxml, "grades.fxml must be available in src/main/resources");

        Parent root = new FXMLLoader(gradesFxml).load();
        interact(() -> stage.setScene(new Scene(root, 1180, 760)));

        Label loggedOutLabel = lookup("#loggedOutLabel").queryAs(Label.class);
        Label topGradesLabel = lookup("#topGradesLabel").queryAs(Label.class);
        TableView<?> gradesTable = lookup("#gradesTable").queryAs(TableView.class);
        ComboBox<?> viewByComboBox = lookup("#viewByComboBox").queryAs(ComboBox.class);
        ComboBox<?> classSelectionComboBox = lookup("#classSelectionComboBox").queryAs(ComboBox.class);
        ComboBox<?> selectionComboBox = lookup("#selectionComboBox").queryAs(ComboBox.class);

        assertTrue(loggedOutLabel.isVisible());
        assertTrue(loggedOutLabel.isManaged());
        assertEquals("User Logged Out", loggedOutLabel.getText());
        assertEquals("No Grades Shown", topGradesLabel.getText());

        assertFalse(gradesTable.isVisible());
        assertFalse(gradesTable.isManaged());
        assertFalse(viewByComboBox.isVisible());
        assertFalse(classSelectionComboBox.isVisible());
        assertFalse(selectionComboBox.isVisible());
    }
}