import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Tests the grade database methods.
 *
 * @author Lily Keus
 * @version 0.1.0
 * @since 8/3/2026
 */

public class GradeDaoTest {

    private Connection connection;
    private GradeDao gradeDao;

    /**
     * Makes a test database before each test.
     */
    @BeforeEach
    public void setUp() throws Exception {
        connection = DriverManager.getConnection("jdbc:h2:mem:gradeTest");

        Statement statement = connection.createStatement();

        statement.execute("DROP TABLE IF EXISTS grades");

        statement.execute(
                "CREATE TABLE grades ("
                        + "grade_id INTEGER "
                        + "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "enrollment_id INTEGER NOT NULL, "
                        + "assignment_id INTEGER NOT NULL, "
                        + "grade DOUBLE NOT NULL, "
                        + "weight DOUBLE NOT NULL"
                        + ")");

        statement.close();

        gradeDao = new GradeDao(connection);
    }

    /**
     * Closes the test database after each test.
     */
    @AfterEach
    public void tearDown() throws Exception {
        connection.close();
    }

    /**
     * Tests adding and finding a grade.
     */
    @Test
    public void insertAndFindTest() throws Exception {
        Grade grade = new Grade(1, 2, 95.5, 0.25);

        gradeDao.insert(grade);

        assertTrue(grade.getGradeId() > 0); // ID test

        Grade savedGrade = gradeDao.findById(grade.getGradeId()); // duplicates grade

        assertNotNull(savedGrade); // null test

        assertEquals(grade.getGradeId(), savedGrade.getGradeId()); // grade ID compare

        assertEquals(1, savedGrade.getEnrollmentId()); // grade EnrollmentID compare

        assertEquals(2, savedGrade.getAssignmentId()); // grade AssignmentID compare

        assertEquals(95.5, savedGrade.getGrade(), 0.001); // grade's grade compare

        assertEquals(0.25, savedGrade.getWeight(), 0.001); // grade weight compare
    }
}