import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests for UserDao, run against an in-memory H2 database.
 *
 * A blank users table is created before each test, and the connection is closed
 * after each test. The test table uses H2 syntax based on the SQLite users
 * table in schema.sql.
 *
 * @author Bay Shahryar
 * @version 0.1.0
 * @since 8/3/26
 */
public class UserDaoTest {

    private Connection connection;
    private UserDao userDao;

    /**
     * Makes a test database before each test.
     */
    @BeforeEach
    public void setUp() throws SQLException {
        connection = DriverManager.getConnection("jdbc:h2:mem:userTest");

        Statement statement = connection.createStatement();
        statement.execute("DROP TABLE IF EXISTS users");
        statement.execute(
                "CREATE TABLE users ("
                        + "user_id INTEGER "
                        + "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "username VARCHAR(50) UNIQUE NOT NULL, "
                        + "password VARCHAR(100) NOT NULL, "
                        + "role VARCHAR(20) NOT NULL"
                        + ")");
        statement.close();

        userDao = new UserDao(connection);
    }

    /**
     * Closes the test database after each test.
     */
    @AfterEach
    public void tearDown() throws SQLException {
        connection.close();
    }

    @Test
    public void insertThenFindById() throws SQLException {
        User inserted = userDao.insert(new User(0, "bay", "pass123", "STUDENT"));
        assertTrue(inserted.getUserId() > 0);

        User found = userDao.findById(inserted.getUserId());
        assertNotNull(found);
        assertEquals("bay", found.getUsername());
        assertEquals("pass123", found.getPassword());
        assertEquals("STUDENT", found.getRole());
    }

    @Test
    public void findByUsername() throws SQLException {
        User inserted = userDao.insert(new User(0, "lily", "secure", "TEACHER"));

        User found = userDao.findByUsername("lily");
        assertNotNull(found);
        assertEquals(inserted.getUserId(), found.getUserId());
        assertEquals("TEACHER", found.getRole());
    }

    @Test
    public void findByUsernameUnknownReturnsNull() throws SQLException {
        assertNull(userDao.findByUsername("nobody"));
    }

    @Test
    public void findByIdUnknownReturnsNull() throws SQLException {
        assertNull(userDao.findById(999));
    }

    @Test
    public void findAllReturnsEveryUser() throws SQLException {
        userDao.insert(new User(0, "ayoung", "p1", "STUDENT"));
        userDao.insert(new User(0, "estefan", "p2", "TEACHER"));

        List<User> users = userDao.findAll();
        assertEquals(2, users.size());
    }

    @Test
    public void updateChangesUser() throws SQLException {
        User inserted = userDao.insert(new User(0, "dave", "oldpass", "STUDENT"));

        boolean updated = userDao.update(
                new User(inserted.getUserId(), "dave2", "newpass", "TEACHER"));
        assertTrue(updated);

        User found = userDao.findById(inserted.getUserId());
        assertEquals("dave2", found.getUsername());
        assertEquals("newpass", found.getPassword());
        assertEquals("TEACHER", found.getRole());
    }

    @Test
    public void updateUnknownReturnsFalse() throws SQLException {
        assertFalse(userDao.update(new User(999, "ghost", "x", "STUDENT")));
    }

    @Test
    public void deleteRemovesUser() throws SQLException {
        User inserted = userDao.insert(new User(0, "eve", "pass", "STUDENT"));

        assertTrue(userDao.delete(inserted.getUserId()));
        assertNull(userDao.findById(inserted.getUserId()));
    }

    @Test
    public void deleteUnknownReturnsFalse() throws SQLException {
        assertFalse(userDao.delete(999));
    }

    @Test
    public void duplicateUsernameRejected() throws SQLException {
        userDao.insert(new User(0, "same", "p1", "STUDENT"));
        assertThrows(SQLException.class,
                () -> userDao.insert(new User(0, "same", "p2", "TEACHER")));
    }
}